[build]
  command = "npm install -g npm@12 && cd src/vanilla && npm ci && npm run build"
  publish = "src/vanilla/dist"

[template.environment]
  LIFF_ID = "Your LIFF ID which is aquired from LINE Dev Center"
